### PR TITLE
Highlight the invalid addresses

### LINKED ISSUE #263: Highlight error addresses when sending coin
Highlight the error destination addresses when sending coins, this is useful especially when sending coins to multiple addresses in advanced mode.

### PR DESCRIPTION
**Pull request by Senyoret1**
Fixes #263

Changes:
- Now, when trying to send coins to multiple destinations with the advanced form, after pressing any of the send buttons all invalid addresses are highlighted.

Does this change need to mentioned in CHANGELOG.md?
No

### CODE REVIEW

**Comment by iketheadore** [comment]
👍 @Senyoret1 can you make the custom change address highlighted when it is invalid too. Thanks a lot.  Also, the coins, users would have a better experience if the invalid coin inputs are highlighted.

**Comment by Senyoret1** [comment]
The last commits include the following changes:

- Now there is a standard way for validating the forms and showing the errors messages in the UI. Whit this, now all the forms show errors messages in the specific problematic fields, to allow the user know which problems have to be solved. This makes it much easier to use not only the forms for sending coins, but all forms in the wallet.

- The return addresses are now validated.

- The form for sending coins now shows clear alerts if the user tries to send more coins or hours than available.

**Comment by Senyoret1** [comment]
The last commits include the following changes:

- The branch was updated and the conflicts were solved.
- Now it is possible to send 0 hours using the advanced form, as with the latest changes it is possible to send 0 hours with the hour allocation slider.
- A unused style was removed.
- Changes for making the prod build procedure work.

**Comment by iketheadore** [comment]
@Senyoret1 please fix the conflicts, thanks.

**Comment by Senyoret1** [comment]
@iketheadore Conflicts solved

**Pull request merged**
