### PR TITLE
Improvements for the desktop wallet

### PR DESCRIPTION
**Pull request by Senyoret1**
Changes:
At this moment, this PR updates the desktop wallet to Angular 8 and includes several changes needed for it to continue working as before. However, the idea is to add additional changes to it, to avoid conflicts with multiple PRs.

Does this change need to mentioned in CHANGELOG.md?
No

### CODE REVIEW

**Comment by Senyoret1** [comment]
The lastest two commits change the background color of the double buttons and prevent the modal windows from being closed when the user clicks the background. This fixes #32 and fixes #11

**Comment by Senyoret1** [comment]
The lastest commit improves the error message shown when there is a problem connecting with the Skywallet Daemon, so it fixes #16 . It also solves a small issue with the white spaces, which was caused by the Angular update and affected the error msg.

**Comment by Senyoret1** [comment]
The lastest commits include the following changes:
- The problem with the "send all" button in the advanced form was solved. This fixes #189
- Now the header only has one menu. This solves #192
- Now the history page does not show all the transactions immediately and some parts of the code were improved. This solves #24

**Comment by iketheadore** [comment]
Looks good to me 👍

I will label it as `WIP` if this PR is still work in progress. Let me know when it's done, I will review again and merge it.

**Comment by Senyoret1** [comment]
The lastest commits include big changes for the form used for sending coins. In fact, now there is only one form, separated in some smaller parts, instead of 2 big forms, as before. The change was made while trying to create a form for creating transactions offline, because the code used by the existing forms was very complicated to maintain and included a lot of repeated code, so creating a new form without improving the code was going to get the situation worse. This change also helps with #194

**Comment by Senyoret1** [comment]
@iketheadore I'm just using this PR to avoid creating a lot of conflicts when adding changes and to avoid having to wait for PRs to me merged before being able to continue changing things, as I'm modifying a lot of different parts. However, you can merge it whenever you want if the Travis tests pass, as I'm trying to solve all bugs before uploading to Github and I can just continue adding changes to another PR.

**Comment by Senyoret1** [comment]
The lastest commit includes a form for creating raw unsigned transactions, a modal window for signing raw transactions and a modal window for sending raw transactions to the network. This makes possible to sign transactions with an offline device. It also includes some improvements for the forms used for sending coins, but there are still some minor problems which will be solved in the next commit.

**Comment by Senyoret1** [comment]
The lastest commit includes the following changes:
- Small problems with the advanced form validation, which appeared only in certain cases, were fixed.
- Some improvements were made to the way in which the forms are resetted.
- Various small errors with the password modal window were fixed.
- Now the modal window for selecting an address for receiving funds does not include unconfirmed addresses from the hw wallets.
- Several other small improvements.

**Comment by Senyoret1** [comment]
The lastest commits include the following changes:

- Some problems with the production builds of the desktop wallet were fixed.
- Electron has been updated to V7 and some problems caused by the update were fixed.

Also, the conflict with https://github.com/SkycoinProject/skycoin/pull/208 was solved. I used the changes made to this PR, as it already included the update of `handlebars` to v4.5.3 and also the changes needed for the app to work with Angular 8.

**Comment by Senyoret1** [comment]
The lastest commit removes a lot of old code used to connect the desktop wallet to the hw wallet via the old (deprecated) JavaScript library. Also, as there are fewer systems to interact with, other parts of the code were simplified.

**Comment by Senyoret1** [comment]
The lastest commit fixes a problem with the unit tests, reactivates an Electron security feature (possible after removing the old code for the JS hw wallet library) and makes a small change to the call to `clearCache` in the Electron code, as the version that was being used was deprecated.

**Comment by Senyoret1** [comment]
The lastest commits include the following changes:
- The buttons are now highlighted during the hover event. This fixes #187 .
- The resizing controls of the `textarea` elements were removed, to help make the interface more consistent.
- Initial steps for making it easier to customize the UI were made. This icludes the creation of a new folder called `customize`, with files which make is possible to change basic parts of the UI with ease.
- Initial improvements were made to the scss files, including removing old unused code (some from the previous design), using variables in some parts insted of hardcoded values, organizing parts of the code in several files and more.

This is just the first part of the general improvements being made to the style files, several other changes have to be made.

**Comment by Senyoret1** [comment]
The lastest commit includes a lot of improvements for almost all the layout files of the desktop wallet. With the changes made, a lot of repeated code was removed, problems were fixed, a lot of values were moved to variables and more. After this, the code is much more consistent and easier to mantain, as there were no real references to make the different parts of the app look relatively similar. Also, the changes make it easier to modify the look of large parts of the app, improves the way in which some parts of the layout handle large texts (important for certain translations) and change the look of some controls to make them look more consistent with the rest of the app.

After the changes, some other problems were found and, as the changes were so many, a some parts should be checked again, so some additional changes should be made, but most of the work with layout files should have already been done in the lastest commit. Some of the pending changes would be: removing some extra layout code, commenting the general styles and creating documentation about how to customize the app.

**Comment by Senyoret1** [comment]
The lastest commit includes the following changes:
- The problems with the e2e test were fixed.
- A lot of small improvements were added to the styles, for improving the consistency of the UI, cleaning the code and fixing small problems.
- The language button on the wizard now has a white background, to ensure it is visible in custom versions of the UI.
- Improvements for the feedback the UI gives to the user when using the mouse to interact with some buttons.
- Basic comments were added to the global scss files.

**Comment by Senyoret1** [comment]
The lastest commit adds the "Scan Addresses" option.

**Comment by Senyoret1** [comment]
The lastest commit changes the way in which most modal windows are openned. Now each modal window has a function for opening it, with some default configuration params, for ensuring more consistency in the app. This change was made in the Skywire Manager. The modal windows for the hw wallet integration were no changed, as these windows are almost always openned by a centralized code.

**Comment by Senyoret1** [comment]
The lastest commit includes the following changes:
- Now the way in which the forms are deactivated while procesing the data is consistent in all the app. Now the fields are always disabled and shown transparent. This allows to have a consistent UI and to avoid some potential errors.
- Now the snackbar is closed faster when running e2e tests, so now protractor does not have to wait too much time and the tests are finished faster. The change was made using an enviroment file, to make it easier to make changes for e2e tests in the future.
- The names of the files related to `SelectAddressComponent` were fixed, as the `.component` parts was missing.
- The modal window with the details for confirming a transaction with the hw wallet now works better with large text.
- The custom component with the modal window for alerting the user about the importance of safeguarding the seed, shown while using the wizard, was removed. Now a standard confirmation message window is used.
- The modal window for selecting an address now shows an info msg if a wallet does not have confirmed addresses.
- Now the qr code buttons are independent components, to avoid repeating a lot of code.
- Some help functions that were not longer useful were removed and the code using them was changed.
- Various additional minor improvements and fixes.

**Comment by Senyoret1** [comment]
The lastest commit includes the following changes:
- A problem with the validation of the send coins form, which appeared only when the usd price was not available, was solved.
- Now it is possible configure the wallet to not retrieve the usd price.
- Small improvements for the header.

**Comment by Senyoret1** [comment]
The lastest commit includes the following changes:
- The structure of the language file was improved. Now it gives much more context about what each text is for, to make it easier to make translations. Also, repeated code was removed and several text were slightly changed so there is a consistent writing style in specific elements of the application.
- The references to an specific coin were removed from the text file and now variables are used, to make it much easier to use the same code base for other Fiber coins.
- The documentation about how to work with the translations files was updated with detailed information about the writing style.
- The Spanish language file was updated, as it was missing several new texts added to the English file and to adapt it to the changes made on this commit.
- Some changes were made in the UI to make it work well with some potential long texts from other languages.

Note: The chinese translation file will need an important update.

**Comment by Senyoret1** [comment]
The lastest commit includes the following changes:
- The red title used in some confirmation modal windows is now much more prominent.
- Improvements for the layout of the error bar shown on the header, to make it able to show long messages.
- Improvements for the form validation on the offline transaction modal windows.
- Improvements for the error management of the send all button.
- Improvements for the button management of the confirmation modal window.
- Several other small improvements and fixes.

**Comment by Senyoret1** [comment]
The lastest commit removes all unused unit test files from the GUI folder, which fixes #191. Only files ending with `.spec.ts` were removed. The 3 files with valid unit tests were not removed and `fdescribe` was replaced with `describe` on them, to maintain the normal functioning of the unit tests system (`fdescribe` makes the it to ignore all other unit tests). All removed files only contained the default unit test, except for `app.component.spec.ts`, which contained outdated tests with didn't work and wasn't valid for a long time ago anyway.

**Comment by Senyoret1** [comment]
The lastest commit changes the way in which errors from connections to the backend and remote services are managed. Now there is a single error class, so the code is now simpler to maintain and underestand. All code reacting to the errors was changed to use the new class and some parts were simplified using the advantages of the new error managements procedures. This fixes #188

**Comment by Senyoret1** [comment]
The lastest group of commits was made for dividing `WalletService` into multiple smaller services. The main problem was that `WalletService` was very big and complex, so working with it was difficult and a lot of unexpected errors could appear, specially taking into account that it did not use strong typing in a lot of functions and that some parts were made very early in development without taking into account current needs. Additionally, some improvements were made to the way in which `WalletService` was working, like using better classes to organize the responses, isolate the core wallet list from the one used to show data to the user (to avoid some unexpected efects when changing some properties) and start removing code from `ApiService` (which contains a lot of unrelated code).

As `WalletService` was the main service used in the app, there were a lot of changes, so I divided them into several commits with somewhat descriptive names, to make it a bit easier to check how the modifications were made. In the first 6 commits the new services are added, modifications are made in various parts of the code to use them and the functionalities are removed from `WalletService`. The next commit finishes the deletion of `WalletService` and the last one fixes the remaining errors and add some improvements. The desktop wallet only works well with the last commit.

Some new services, like `WalletsAndAddressesService` and `BalanceAndOutputsService`, have important changes compared to how the functionalities worked on `WalletService`, to improve both the code and how the application works (including some edge cases), but others remain very similar to the implementation on `WalletService`. It was done that way to focus mainly on how the wallets and the balance are managed, which had a lot of room for improvement, and not overcomplicate the commits while separating other parts from `WalletService`. This means that there is still room for improvement in the new services, but the application itself is working well.

**Comment by Senyoret1** [comment]
The lastest commit includes the following changes:

- Some parts of the code were moved to improve the separation of concerns.
- Fixes a problem which prevented the app to start when there was no previously saved data.
- Fixes a simple but hard to find error which prevented the e2e test to run, as it made Protractor to wait indefinitely for the balance to be updated.
- Removes the need to get the price information from a remote server while running the e2e test, to improve the response times and prevent the tests to fail while the service is not responding.
- Some additional changes.

**Comment by Senyoret1** [comment]
The lastest commit adds several improvements and comments to some of the most important services of the desktop wallet. The improvements include removing unused code, adding better separation of concerns, better use of types and diferent kinds of optimizations. The changes were made while reviewing all the code, to make sure everything is working as it sould, the code has aceptable quality and there are no errors left from previous modifications. The idea started by this commit is to review all the code again, because a lot of changes were made recently, but also use the oportunity to document the code and fix some simple errors that were left behind. The first parts to be reviewed and changed are the services, because the services are some of the most complex parts of the app and if a new error is introduced on any of them it should be easy to detected it while checking more specific parts of the aplication.

The comments added to the code are mainly for describing the classes, functions and properties, which should help a lot for underestanding the code while not being excessively annoying when making modifications to it.

The commit also includes changes to the code affected by the modifications made to the services, so the application should continue working well.

**Comment by Senyoret1** [comment]
The lastest commits include the following changes:
- `HistoryService` and `SpendingService` were documented and improved.
- New objects for managing the transactions were created and are now being used on the app. The new objects were made to isolate the data used on the app from the objects returned by the node, to avoid multiple potential problems and improve the readability of the code.
- Various calculations were moved to the services related to the transactions, to improve the separation of concerns.
- All the code affected by the changes made to the services was checked and modified as needed.
- Some other small improvements.

**Comment by Senyoret1** [comment]
The lastest 3 commits include the following changes:
- A problem with the compiler complaining while creating prod builds was solved.
- `NetworkService` and `AppService` were improved and commented.
- The `Connection` object was moved from `app.datatypes.ts` and improved (to add missing properties and isolate the data from the node responses), while other objects were removed (for not being really needed).
- Some calculations are now made directly inside the services, to improve the separation of concerns.
- The way in which the connections list is updated periodically is now much more reliable, avoiding racing conditions and recovering itself in case of errors.
- Some improvements to how errors on `AppService` are informed were made.
- Some other small improvements.

**Comment by Senyoret1** [comment]
The lastest 2 commits include the following changes:
- Several services were commented and received improvements.
- Important changes were made to `PriceService`, to make the periodical data update procedure much more robust and efficient.
- `NavBarService` was renamed to `NavBarSwitchService`, as the previous name was not really indicative of the real objetive of the service.
- `BlockchainService` was changed a lot to improve it, remove unrelated properties, use better types and more.

**Comment by Senyoret1** [comment]
The lastest commit includes the following changes:
- The utility functions have been improved and commented.
- Parts of the error processing code were moved and removed.
- The property for identifying the category of the errors was removed, as was not being used or nedded.
- The `semver.ts` and `index.ts` utility files were combined into the new `general-utils.ts` file.

**Comment by iketheadore** [comment]
👍Good work

**Pull request merged**
